// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-yCpvTvHkcHqG2IyeDfninAVli2zoX7A',
    appId: '1:939709975569:web:7761bd81b6a4be3e8275b0',
    messagingSenderId: '939709975569',
    projectId: 'orc-app-3f68b',
    authDomain: 'orc-app-3f68b.firebaseapp.com',
    storageBucket: 'orc-app-3f68b.appspot.com',
    measurementId: 'G-BX35MJYG22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSa1RZiHArdTicAK_7Yz02Jwwvz9dYsYI',
    appId: '1:939709975569:android:82ddfb67d897012a8275b0',
    messagingSenderId: '939709975569',
    projectId: 'orc-app-3f68b',
    storageBucket: 'orc-app-3f68b.appspot.com',
  );
}
